services:
  celery_worker:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: celery_worker
    command: uv run uvicorn src.main:app --host 0.0.0.0 --port ${API_PORT} --reload
    environment:
      - PYTHONDONTWRITEBYTECODE=1
    env_file:
      - .env
    ports:
      - "${API_PORT}:${API_PORT}"
    develop:
      watch:
        - action: sync
          path: ./src
          target: /app/src
        - action: sync
          path: ./pyproject.toml
          target: /app/pyproject.toml
        - action: sync
          path: ./uv.lock
          target: /app/uv.lock
        - action: rebuild
          path: Dockerfile
