[project]
name = "celery-worker"
version = "0.1.0"
description = "Celery Worker"
requires-python = ">=3.14"
dependencies = [
    "celery>=5.6.0",
    "fastapi>=0.123.5",
    "uvicorn[standard]==0.32.0",
]

[dependency-groups]
dev = [
    "ruff>=0.14.8",
]

